# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TicTacToe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TicTacToe(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 200)
        Dialog.setMinimumSize(QtCore.QSize(200, 200))
        Dialog.setMaximumSize(QtCore.QSize(200, 200))
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 20, 164, 164))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton11 = QtWidgets.QPushButton(self.widget)
        self.pushButton11.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton11.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton11.setText("")
        self.pushButton11.setFont(QtGui.QFont('Arial', 15))
        self.pushButton11.setObjectName("pushButton11")
        self.gridLayout.addWidget(self.pushButton11, 0, 0, 1, 1)
        self.pushButton12 = QtWidgets.QPushButton(self.widget)
        self.pushButton12.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton12.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton12.setText("")
        self.pushButton12.setObjectName("pushButton12")
        self.pushButton12.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton12, 0, 1, 1, 1)
        self.pushButton13 = QtWidgets.QPushButton(self.widget)
        self.pushButton13.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton13.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton13.setText("")
        self.pushButton13.setObjectName("pushButton13")
        self.pushButton13.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton13, 0, 2, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.widget)
        self.pushButton21.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton21.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton21.setText("")
        self.pushButton21.setObjectName("pushButton21")
        self.pushButton21.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton21, 1, 0, 1, 1)
        self.pushButton22 = QtWidgets.QPushButton(self.widget)
        self.pushButton22.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton22.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton22.setText("")
        self.pushButton22.setObjectName("pushButton22")
        self.pushButton22.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton22, 1, 1, 1, 1)
        self.pushButton23 = QtWidgets.QPushButton(self.widget)
        self.pushButton23.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton23.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton23.setText("")
        self.pushButton23.setObjectName("pushButton23")
        self.pushButton23.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton23, 1, 2, 1, 1)
        self.pushButton31 = QtWidgets.QPushButton(self.widget)
        self.pushButton31.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton31.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton31.setText("")
        self.pushButton31.setObjectName("pushButton31")
        self.pushButton31.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton31, 2, 0, 1, 1)
        self.pushButton32 = QtWidgets.QPushButton(self.widget)
        self.pushButton32.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton32.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton32.setText("")
        self.pushButton32.setObjectName("pushButton32")
        self.pushButton32.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton32, 2, 1, 1, 1)
        self.pushButton33 = QtWidgets.QPushButton(self.widget)
        self.pushButton33.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton33.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton33.setText("")
        self.pushButton33.setObjectName("pushButton33")
        self.pushButton33.setFont(QtGui.QFont('Arial', 15))
        self.gridLayout.addWidget(self.pushButton33, 2, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Tic-Tac-Toe"))
